### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by giuliaok** [giuliaok/crawls_nest#1]
What needs to be done, as of Jan 2024. 

### DATA - for project to be self contained:
- [ ] Allow for text classification prompt to be user defined
- [ ] Clean schema 
- [ ] Eliminate case sensitivity in the --geography argument 
- [ ] In ColumnarExplorer, ask if the users want to continue when a crawl is composed by more than 1 month (e.g. September/October 2023)
- [ ] Allow users to decide whether to merge webpages into websites or not - relevant for text classification. The function to do so is ```website_aggregator``` within ```utils.py```
- [ ] allow for LLM to be user defined
- [ ] Write robustness tests
- [ ] Write exceptions for all potentially unstable functions
- [ ] add shapefile for each Local Authority
- [ ] Return 'no distinctive postcode available for this local authority' when no distinctive postcode available for a local authority
